Readme rewrite
openweathermap/deker-tools pull request #8
Opened 2023-08-17 15:14 UTC by singular0

2023-08-17 17:37 UTC, SerGeRybakov submitted a review, later dismissed

2023-08-17 22:00 UTC, SerGeRybakov requested changes
To my mind any readme **must help** undestanding the contents and aims of the project.
I think, we shall discuss this fix.

2023-08-17 22:00 UTC, SerGeRybakov commented on README.md
> +# Deker Utility Functions
I'm sure, that there is no reason to rename the project, repo and package.

2023-08-17 22:00 UTC, SerGeRybakov commented on README.md
> -```
What was the reason to remove the examples? This package is independent from any other Deker deps and can be used in any project, not related to Deker. Any developer, who managed to reach this readme, could have a fast look over the examples and understand how to use this or that function. Without examples the repo became muted.

2023-08-18 07:41 UTC, matveyvarg commented on README.md
> +# Deker Utility Functions
+1

2023-08-18 07:45 UTC, matveyvarg commented on README.md
> -```
IMHO, it's not a big deal as we have link to the documentation. However, I would agree with @SerGeRybakov. I believe that it's better to keep at least some examples here.

2023-08-18 08:03 UTC, singular0 commented on README.md
> -```
According to Deker documentation API of this package is not stable, so I this contradicts an idea to spin it off into separate self-sufficient project

2023-08-18 09:28 UTC, SerGeRybakov approved these changes

2023-08-18 09:28 UTC, merged